const Map<String, String> enUS = {
  "new_user": "New User",
  "sign_up": "Sign Up",
  "phone_number": "Phone Number",
  "enter_valid_mobile": "Please enter correct Phone Number",
  "password": "Password",
  "enter_valid_password": "Please enter correct password",
  "login": "Login",
  "forgot_password": "Forgot Password",
  "mobile_verification": "Mobile Verification",
  "enter_phone_number": "Enter Phone Number",
  "10_digit_phone_number": "Please enter 10 digit phone number",
  "send_otp": "Send OTP",
  "back": "Back",
  "phone_no": "Phone No",
  "otp": "OTP",
  "confirm_password": "Confirm Password",
  "verify": "Verify",
  "enter_correct_otp": "Please enter correct OTP",
  "firstName": "First Name",
  "lastName": "Last Name",
  "enter_valid_name": "Enter Valid Name",
  "enter_valid_last_name": "Enter Valid Last Name",
  "email": "Email",
  "enter_valid_email": "Enter Valid Email",
  "gender": "Gender",
  "select_gender": "Select Gender",
  "user_name": "User Name",
  "enter_valid_username": "Enter Valid User Name",
  "verified": "Verified",
  "dob": "Date of Birth",
  "6_letter_password": 'Password must be at least 6 characters',
  "password_must_contain_special_character":
      'Password must contain at least\none special character',
  "password_cannot_have_space": 'Password cannot contain spaces',
  "password_and_confirm_password_error":
      "Password and confirm password\nshould be same",
  "sign_in": "Sign In",
  "internet_not_available": "Internet Not Available",
  "something_went_wrong": "Something Went Wrong. Try again later.",
  "reset_password": "Reset Password",
  "enjoying_cou_cou": "Enjoying Cou Cou!",
  "tap_star_to_rate": "Tap a star to rate it on the\nApp Store",
  "view_all": "View All",
  "view_challenge": "View Challenge",
  "1st_prize": "1st Prize",
  "2nd_prize": "2nd Prize",
  "3rd_prize": "3rd Prize",
  "latest_post": "Latest Posts",
  "share": "Share",
  "more": "more",
  "less": "less",
  "update_address": "Update Address",
  "policy_tc": "Policy, T&C",
  "support": "Support",
  "logout": "Logout",
  "logout_from_cou_cou": "Logout from CouCou?",
  "you_wont_receive_existing":
      "You won't receive any new exiting deals and offers.",
  "cancel": "Cancel",
  "app_version": "App Version",
  "posts": "Posts",
  "edit": "Edit",
  "delete": "Delete",
  "select_img_where_you_want_to_pickup":
      "Select from where you want to pickup file",
  "camera": "Camera",
  "gallery": "Gallery",
  "select_img": "Select Image",
  "comments": "Comments",
  "your_comment": "Your Comment...",
  "notifications": "Notification",
  "my_activity": "My Activity",
  "other_activity": "Other Activity",
  "liked_your_post": "liked your Post",
  "you_have_liked_on": "You have liked on",
  "you_have_commented_on": "You have commented on",
  "comment_on_your_post": "commented on your Post",
  "top_5_post": "Top 5 Post",
  "all_challenges": "All Challenges",
  "no_data_available": "No Data Available",
  "clear": "Clear",
  "select_audio_file_less_than_5": "Select audio file less than 5 mb",
  "location": "Location",
  "enter_your_addr": "Enter your address",
  "recipe_location": "Recipe Location",
  "choose_challenge": "Choose your challenge",
  "select_challenge": "Select Challenge",
  "caption": "Caption",
  "max_250_words": "max 250 words",
  "submit": "Submit",
  "your_post": "Your Post",
  "successfully": "Successfully",
  "uploaded": "Uploaded",
  "updated": "Updated",
  "okay": "Okay",
  "language": "Language",
  "select_source": "Select Source",
  "select_img_or_vid": "Select Image or Video",
  "image": "Image",
  "video": "Video",
  "participate_and_win": "Participate and win",
  "profile": "Profile",
  "participate_now": "Participate Now",
  "mobile_number": "Mobile Number",
  "enter_valid_otp": "Enter valid OTP",
  "user_name_2": "Username",
  "details": "Details",
};
