const Map<String, String> enUS = {
  "new_user": "New User",
  "sign_up": "Sign Up",
  "phone_number": "Phone Number",
  "enter_valid_mobile": "Please enter correct Phone Number",
  "password": "Password",
  "enter_valid_password": "Please enter correct password",
  "login": "Login",
  "forgot_password": "Forgot Password",
  "mobile_verification": "Mobile Verification",
  "enter_phone_number": "Enter Phone Number",
  "10_digit_phone_number": "Please enter 10 digit phone number",
  "send_otp": "Send OTP",
  "back": "Back",
  "phone_no": "Phone No",
  "otp": "OTP",
  "confirm_password": "Confirm Password",
  "verify": "Verify",
  "enter_correct_otp": "Please enter correct OTP",
  "firstName": "First Name",
  "lastName": "Last Name",
  "enter_valid_name": "Enter Valid Name",
  "enter_valid_last_name": "Enter Valid Last Name",
  "email": "Email",
  "enter_valid_email": "Enter Valid Email",
  "gender": "Gender",
  "select_gender": "Select Gender",
  "user_name": "User Name",
  "enter_valid_username": "Enter Valid User Name",
  "verified": "Verified",
  "dob": "Date of Birth",
  "6_letter_password": 'Password must be at least 6 characters',
  "password_must_contain_special_character":
      'Password must contain at least\none special character',
  "password_cannot_have_space": 'Password cannot contain spaces',
  "password_and_confirm_password_error":
      "Password and confirm password\nshould be same",
  "sign_in": "Sign In",
  "internet_not_available": "Internet Not Available",
  "something_went_wrong": "Something Went Wrong. Try again later.",
  "reset_password": "Reset Password",
  "enjoying_cou_cou": "Enjoying Cou Cou!",
  "tap_star_to_rate": "Tap a star to rate it on the\nApp Store",
  "view_all": "View All",
  "1st_prize": "1st Prize",
  "2nd_prize": "2nd Prize",
  "3rd_prize": "3rd Prize",
  "latest_post": "Latest Posts",
  "share": "Share",
  "more": "more",
  "less": "less",
  "update_address": "Update Address",
  "policy_tc": "Policy, T&C",
  "support": "Support",
  "logout": "Logout",
  "logout_from_cou_cou": "Logout from CouCou?",
  "you_wont_receive_existing":
      "You won't receive any new exiting deals and offers.",
  "cancel": "Cancel",
  "app_version": "App Version",
  "posts": "Posts",
  "edit": "Edit",
  "delete": "Delete",
  "select_img_where_you_want_to_pickup":
      "Select from where you want to pickup file",
  "camera": "Camera",
  "gallery": "Gallery",
  "select_img": "Select Image",
  "comments": "Comments",
  "your_comment": "Your Comment...",
  "notifications": "Notification",
  "my_activity": "My Activity",
  "other_activity": "Other Activity",
  "liked_your_post": "liked your Post",
  "you_have_liked_on": "You have liked on",
  "you_have_commented_on": "You have commented on",
  "comment_on_your_post": "commented on your Post",
  "top_5_post": "Top 5 Post",
  "all_challenges": "All Challenges",
  "no_data_available": "No Data Available",
  "clear": "Clear",
  "select_audio_file_less_than_5": "Select audio file less than 5 mb",
  "location": "Location",
  "enter_your_addr": "Enter your address",
  "recipe_location": "Recipe Location",
  "choose_challenge": "Choose your challenge",
  "select_challenge": "Select Challenge",
  "caption": "Caption",
  "max_250_words": "max 250 words",
  "submit": "Submit",
  "your_post": "Your Post",
  "successfully": "Successfully",
  "uploaded": "Uploaded",
  "updated": "Updated",
  "okay": "Okay",
  "language": "Language",
  "select_source": "Select Source",
  "select_img_or_vid": "Select Image or Video",
  "image": "Image",
  "video": "Video"

  // "new_user_sign_up": "New User? Sign Up",
  // "verify_phone_number": "Verify Phone Number",
  // "we_send_otp": "We'll send an OTP\non your Phone Number",
  // "enter_registered_number": "Enter your registered\nPhone Number",
  // "reset_your_password": "Reset Your Password",
  // "set_new_password": "Set a new password\nfor your account",
  // "confirm": "Confirm",
  // "bio": "Bio",
  // "website": "Website",
  // "challenge_name": "Challenge Name",
  // "theme": "Theme",
  // "enter_valid_value": "Enter Valid Value",
  // "challenge_last_date": "Challenge Last Date",
  // "description": "Challenge Description",
  // "enter_valid_description": "Enter Valid Description",
  // "create": "Create",
  // "public": "Public",
  // "hidden": "Hidden",
  // "bookmarks": "Bookmarks",
  // "reward_description": "Reward Description",
  // "rewards_available": "Rewards Available?",
  // "yes": "Yes",
  // "no": "No",
  // "video": "Video",
  // "picture": "Picture",
  // "challenge_format": "Challenge Format",
  // "upload": "Upload",
  // "enter_valid_address": "Enter Valid Address",
  // "address": "Address",

  // // -------------
  // "email_is_not_register": "Email is not register. Kindly Sign Up.",
  // "cannot_fetch_email_provider":
  //     "Cannot fetch your Email from this Login Provider",
  // "new_user_auth": "New User Registration",
  // "dish_name": "Dish Name",
  // "prepration_time": "Preparation Time",
  // "price": "Price",
  // "serves": "Serves",
  // "cart": "Cart",
  // "your_cart_is_empty":
  //     "You Cart is Empty. To Add Item to Cart Go To Explore Section inside Hungry Tab.",
  // "add_instruction": "Add Instruction",
  // "write_caption": "Write Caption here",
  // "delivery_option": "Delivery Option",
  // "item_price": "Item Price",
  // "delivery_charges": "Delivery Charges",
  // "total_price": "Total Price",
  // "please_choose_addr": "Please choose or add address",
  // "pay_now": "Pay Now",
  // "addr": "Address",
  // "choose_addr": "Choose Address",
  // "add_new_addr": "Add New Address",
  // "payment_success": "Your Payment is Successful",
  // "pay_failed": "Payment Failed.",
  // "email_us_on": "Please Email us on",
  // "problem_still_exist": "If Problem still persists",
  // "ok": "Ok",
  // "challenge_expire_on": "Challenge Expires on",
  // "reward_avail": "Rewards Available",
  // "video_selected": "Video Selected",
  // "select_video": "Select Video",
  // "select_video_for_challenge": "Select a video for challenge",
  // "create_reel": "Create Reel",
  // "tap_a_camera": "Tap a camera",
  // "edit_post": "Edit Post",
  // "tag_people": "Tag People",
  // "add_loc": "Add Location",
  // "some_field_are_missing": "Some field are missing or has wrong input",
  // "please_add_loc": "Please add Location",
  // "post_updated_success": "Post Updated Successfully",
  // "post_created_success": "Post Created Successful.",
  // "upload_as": "Upload as",
  // "users": "Users",
  // "anonymous": "Anonymous",
  // "want_to_sell": "Want to sell ?",
  // "question": "Question",
  // "write_your_quest": "Write your Question",
  // "option_a": "Option A",
  // "option_b": "Option B",
  // "add_caption": "Add Caption",
  // "add_more_item": "Add more Items",
  // "post": "Post",
  // "add_dish_detail": "Add Dish Detail",
  // "please_select_delivery_option": "Please Select Delivery options.",
  // "save": "Save",
  // "food_type": "Food Type ?",
  // "veg": "Veg",
  // "non_veg": "Non-Veg",
  // "name_of_dish": "Name of Dish",
  // "please_enter_dish_name": "Please enter Dish Name",
  // "please_enter_valid_dish_name": "Enter a Valid Dish Name",
  // "cost": "Cost",
  // "in_rs": "In Rs",
  // "please_enter_dish_cost": "Please enter Dish Cost",
  // "please_enter_valid_dish_cost": "Enter a Valid Dish Cost",
  // "quantity": "Quantity",
  // "please_enter_quantity": "Please enter Quantity",
  // "please_enter_valid_quantity": "Enter a Valid Quantity",
  // "prepration_time_in_min": "Preparation Time (In minute)",
  // "please_enter_prepration_time": "Please enter Preparation Time",
  // "enter_valid_prepration_time": "Enter a Valid Preparation Time",
  // "serve_per_person": "Serves per Person",
  // "please_enter_serves_per_person": "Please enter Serve per Person",
  // "enter_valid_serves_per_person": "Enter a Valid Serve per Person",
  // "search": "Search",
  // "item_already_exist_in_cart": "Item Already Exist in Cart",
  // "added_to_cart": "Added To Cart",
  // "add_to_cart": "Add To Cart",
  // "no_challenges_avail": "No Challenges Available",
  // "refresh": "Refresh",
  // "all": "All",
  // "active": "Active",
  // "closed": "Closed",
  // "reward": "Rewards",

  // "write_a_comment": "Write a comment",
  // "like": "Likes",
  // "view_comment": "View Comments",
  // "available": "Available",
  // "qty_avail": "Quantity Available",
  // "share_post": "Share Post",
  // "bookmark": "Bookmark",
  // "report_post": "Report Post",
  // "explore": "Explore",

  // "buy": "Buy",
  // "sell": "Sell",
  // "data_not_found": "Data Not Found.",
  // "order_id": "Order Id",
  // "item_name": "Item Name",
  // "kitchen_addr": "Kitchen Address",
  // "delivering_to": "Delivering to",
  // "intruction": "Instruction",
  // "gov_gst": "Gov. Gst",
  // "my_order": "My Orders",
  // "search_user": "Search Users",
  // "setting": "Settings",
  // "choose_option": "Choose Options",
  // "capture_img": "Capture Image",
  // "capture_vid": "Capture Video",
  // "select_vid": "Select Video",
  // "my_followers": "My Followers",
  // "my_following": "My Followings",
  // "followers": "Followers",
  // "following": "Following",
  // "follow": "Follow",
  // "descp": "Description",
  // "you_will_get_reward_after_wining_this_challenge":
  //     "Note: You will get a Reward after winning this challenge!",
  // "reward_are": "Rewards are",
  // "chats": "Chats",
  // "group": "Groups",

  // "enter_group_name": "Enter a group name",
  // "provide_group_name_optional_image":
  //     "Provide a group name and a optional image",
  // "select_group_image": "Select a Group Image",
  // "participants": "Participants",
  // "new_group": "New Group",
  // "group_name_cant_be_empty": "Group name can't be empty",
  // "type_message": "Type Message",
  // "create_group": "Create Group",
  // "select_atleast_2_members":
  //     "You need to add atleast 2 members for creating group",
  // "you_have_not_selected_members": "You haven't selected any member to add",
  // "add": "Add",
  // "next": "Next",
  // "deleted": "Deleted",
  // "no_conversations": "No Conversations",
  // "create_new_group": "Create New Group",
  // "delete_group": "Delete Group",
  // "admin": "Admin",
  // "update_group_name": "Update Group Name",
  // "group_will_be_deleted": "The group will be deleted and cannot be recovered",
  // "cou_cou": "Cou Cou",
  // "challenges": "Challenges",
  // "hungry": "Hungry",
  // "loading": "Loading",
  // "days_ago": "days ago",
  // "hr_ago": "hr ago",
  // "min_ago": "min ago",
  // "my_addr": "My Address",
  // "add_addr": "Add Address",

  // "this_challenge_is_expired": "This challenge is expired",
  // "no_reels_avail": "No Reels Available",
  // "could_not_connect_to_internet": "Could not connect to internet",
  // "order_placed_on": "Order Placed On",
  // "participate_now": "Participate Now",
  // "winners": "Winners",
  // "spotlight": "Spotlight",
  // "leave_group": "Leave Group",
  // "select_images": "Select Images",
  // "please_select_img_to_proceed": "Please select image to proceed.",
  // "copy_link": "Copy Link",
  // "link_not_avail": "Link not available",
  // "link_copy": "Link Copied",
  // "participate_challenge": "Participate Challenge",
  // "sponsored_by": "Sponsored By",
  // "delete_story_dialog_content": "Are you sure you want to delete this story?",
  // "delete_challenge_dialog_content":
  //     "Are you sure you want to delete this challenge?",
  // "delete_challenge_video_dialog_content":
  //     "Are you sure you want to delete this challenge video?",
  // "unit": "Unit",
};
