const Map<String, String> mrIN = {
  "new_user": "नवीन युजर ?",
  "sign_up": "साईन अप करा",
  "phone_number": "फ़ोन नंबर",
  "enter_valid_mobile": "कृपया मोबाईल नंबर बरोबर प्रविष्ट करा",
  "password": "पासवर्ड",
  "enter_valid_password": "कृपया पासवर्ड बरोबर प्रविष्ट करा",
  "login": "लॉग इन करा",
  "forgot_password": "पासवर्ड विसरलात ?",
  "mobile_verification": "मोबाइल व्हेरिफाय करा",
  "enter_phone_number": "फोन नंबर टायपिंग करा",
  "10_digit_phone_number": "कृपया १० अंकी मोबाईल नंबर प्रविष्ट करा",
  "send_otp": "ओटीपी पाठवा",
  "back": "मागे जा",
  "phone_no": "फोन नंबर",
  "otp": "ओटीपी",
  "confirm_password": "पासवर्ड की व्हेरिफाय करा",
  "verify": "व्हेरिफाय करा",
  "enter_correct_otp": "कृपया ओटीपी बरोबर प्रविष्ट करा",
  "firstName": "पहिलं नाव",
  "lastName": "शेवटचं नाव",
  "enter_valid_name": "नाव बरोबर प्रविष्ट करा",
  "enter_valid_last_name": "शेवटचं नाव बरोबर प्रविष्ट करा",
  "email": "ईमेल",
  "enter_valid_email": "बरोबर युजर इमेल आयडी प्रविष्ट करा",
  "gender": "लिंग",
  "select_gender": "लिंग निवडा",
  "user_name": "युजर नेम",
  "enter_valid_username": "बरोबर युजर नेम प्रविष्ट करा",
  "verified": "व्हेरिफाय",
  "dob": "जन्म तारीख",
  "6_letter_password": "पासवर्ड कमीत कमी 6 अक्षरी असणे आवश्यक आहे",
  "password_must_contain_special_character":
      "पासवर्ड मध्ये किमान एक स्पेशल अक्षर असणे आवश्यक आहे",
  "password_cannot_have_space": "पासवर्ड मध्ये जागा (स्पेस) सोडून नये",
  "password_and_confirm_password_error":
      "पासवर्ड आणि कन्फर्म पासवर्ड एक सारखा असणे गरजचं आहे",
  "sign_in": "साईइन  करा",
  "internet_not_available": "इंटरनेट उपलब्ध नाही",
  "something_went_wrong": "काही तरी चुकीचे आहे पुन्हा प्रयत्न करा.",
  "reset_password": "पासवर्ड रीसेट करा",
  "enjoying_cou_cou": "Cou Cou चा आनंद घ्या !",
  "tap_star_to_rate":
      "प्ले स्टोअर वर ऍप ला रेटिंग देण्यासाठी स्टार वर क्लिक करा",
  "view_all": "सर्व पहा",
  "1st_prize": "प्रथम बक्षीस",
  "2nd_prize": "दुसरे बक्षीस",
  "3rd_prize": "तिसरे बक्षीस",
  "latest_post": "नवीन पोस्ट",
  "share": "शेयर",
  "more": "जास्त",
  "less": "कमी",
  "update_address": "नवीन पत्ता",
  "policy_tc": "धोरण, T&C",
  "support": "मदत",
  "logout": "लॉग आउट",
  "logout_from_cou_cou": "CouCou मधुन बाहेर पडायचे आहे का..?",
  "you_wont_receive_existing": "मिळवा नवीन आकर्षक डिल आणि ऑफर.",
  "cancel": "कॅन्सल करा",
  "app_version": "ऍप व्हर्जन",
  "posts": "पोस्ट",
  "edit": "एडिट",
  "delete": "डिलिट",
  "select_img_where_you_want_to_pickup": "तुम्ही फाईल अपलोड साठी लोकेशन निवडा",
  "camera": "कॅमेरा",
  "gallery": "गॅलरी",
  "select_img": "इमेज निवडा",
  "comments": "कॉमेंट्स",
  "your_comment": "तुमचे कमेंट्स...",
  "notifications": "नोटिफिकेशन",
  "my_activity": "माझे नोटिफिकेशन",
  "other_activity": "इतर नोटिफिकेशन",
  "liked_your_post": "तुमच्या पोस्ट वरील लाईक",
  "you_have_liked_on": "तुम्ही लाइक केलेले",
  "you_have_commented_on": "तुम्ही कमेंट केलेले",
  "comment_on_your_post": "तुमच्या पोस्ट वरील कमेंट्स",
  "top_5_post": "टॉप 5 पोस्ट",
  "all_challenges": "सर्व चॅलेंज",
  "no_data_available": "डेटा उपलब्ध नाही",
  "clear": "क्लिअर करा",
  "select_audio_file_less_than_5": "कृपया ऑडिओ फाईल ५ mb चा खालील असावी",
  "location": "लोकेशन",
  "enter_your_addr": "पत्ता टायपिंग करा",
  "recipe_location": "रेसिपी लोकेशन",
  "choose_challenge": "तुमचं चॅलेंज निवडा",
  "select_challenge": "तुमचं चॅलेंज निवडा",
  "caption": "कैप्शन",
  "max_250_words": "कमाल 250 शब्द",
  "submit": "सबमिट",
  "your_post": "तुमची पोस्ट",
  "successfully": "यशस्वीरित्या",
  "uploaded": "अपलोड झाली",
  "updated": "अपडेट झालेला आहे",
  "okay": "ठीक आहे",
  "language": "भाषा",

//   "phone_number": "फोन नंबर",
//   "enter_valid_mobile": "योग्य मोबाईल डायल करा",
//   "password": "पासवर्ड",
//   "confirm_password": "कन्फर्म पासवर्ड",
//   "verify": "सत्यापित करा",
//   "firstName": "प्रथम नाव",
//   "lastName": "आडनांव",
//   "enter_valid_name": "योग्य नाव इंटर करा",
//   "enter_valid_last_name": "योग्य आडनांव इंटर करा",
//   "enter_valid_password": "योग्य पासवर्ड इंटर करा",
//   "password_and_confirm_password_error": "पासवर्ड आणि कन्फर्म पासवर्ड एरर",
//   "email": "ईमेल",
//   "enter_valid_email": "योग्य ईमेल इंटर करा",
//   "gender": "लिंग",
//   "select_gender": "लिंग निवडा",
//   "user_name": "वापरकर्ता नाव",
//   "enter_valid_username": "योग्य युजर नाव डायल करा",
//   "login": "लॉगिन",
//   "new_user_sign_up": "नवीन युजर रजिस्टर?",
//   "forgot_password": "विस्मरण_पासवर्ड",
//   "verify_phone_number": "मोबाईल नंबर तपासून पाहा",
//   "we_send_otp": "आम्ही ओटीपी पाठवला आहे",
//   "enter_registered_number": "रजिस्टर मोबाइल नंबर डायल करा",
//   "mobile_verification": "मोबाइल_व्हेरिफिकेशन",
//   "enter_correct_otp": "योग्य ओटिपी डायल करा",
//   "reset_your_password": "पासवर्ड बदला",
//   "set_new_password": "नवीन पासवर्ड ठेवा",
//   "confirm": "पुष्टि करा",
//   "submit": "सबमिट करा",
//   "bio": "बायो",
//   "website": "वेबसाइट",
//   "challenge_name": "चॅलेंज_नाव",
//   "theme": "थीम",
//   "enter_valid_value": "योग्य डायल करा",
//   "challenge_last_date": "चॅलेंज शेवटीची तारीख",
//   "description": "चॅलेंज वर्णन",
//   "enter_valid_description": "योग्य वर्णन लिहा",

//   "create": "तयार करा",
//   "reward_description": "बक्षीस स्वरूप",
//   "rewards_available": "बक्षीस उपलब्ध",
//   "yes": "होय",
//   "no": "नाही",
//   "video": "व्हिडिओ",
//   "picture": "फोटो",
//   "challenge_format": "चॅलेंज स्वरूप",
//   "upload": "अपलोड",
//   "caption": "माहिती",
//   "enter_valid_address": "योग्य पत्ता डायल करा",
//   "address": "पत्ता",

// // -------------
//   "email_is_not_register": "ईमेल नोंदणीकृत नाही. कृपया नोंदणी करा.",
//   "internet_not_available": "इंटरनेट उपलब्ध नाही",
//   "something_went_wrong": "काहीतरी चूक झाली.नंतर पुन्हा प्रयत्न करा.",
//   "cannot_fetch_email_provider":
//       "या लॉगिन प्रदात्याकडून तुमचा ईमेल आणू शकत नाही",
//   "new_user_auth": "नवीन वापरकर्ता नोंदणी",
//   "dish_name": "डिशचे नाव",
//   "prepration_time": "तयारीची वेळ",
//   "price": "किंमत",
//   "serves": "किती माणसांसाठी ?",
//   "cart": "कार्ट",
//   "your_cart_is_empty":
//       "तुम्ही कार्ट रिकामे आहे. कार्टमध्ये आयटम जोडण्यासाठी हंग्री टॅबमधील विभाग एक्सप्लोर करण्यासाठी जा",
//   "add_instruction": "सूचना जोडा",
//   "write_caption": "येथे माहिती लिहा",
//   "delivery_option": "डिलिव्हरी पर्याय",
//   "item_price": "वस्तूची किंमत",
//   "delivery_charges": "डिलिव्हरी चार्जेस",
//   "total_price": "एकूण किंमत",
//   "please_choose_addr": "कृपया पत्ता निवडा किंवा पत्ता ऍड करा ",
//   "pay_now": "पैशे आता द्या",
//   "addr": "पत्ता",
//   "choose_addr": "पत्ता निवडा",
//   "add_new_addr": "नवीन पत्ता जोडा",
//   "payment_success": "तुमचे पेमेंट यशस्वी झाले आहे",
//   "back": "मागे",
//   "pay_failed": "पेमेंट अयशस्वी.",
//   "email_us_on": "कृपया आम्हाला ईमेल करा",
//   "problem_still_exist": "समस्या अजूनही कायम राहिल्यास",
//   "ok": "ठीक आहे",
//   "challenge_expire_on": "चॅलेंजची मुदत संपेल",
//   "reward_avail": "बक्षीस उपलब्ध",
//   "video_selected": "व्हिडिओ निवडला",
//   "select_video": "व्हिडिओ निवडा",
//   "select_video_for_challenge": "चॅलेंजसाठी व्हिडिओ निवडा",
//   "create_reel": "रील तयार करा",
//   "tap_a_camera": "कॅमेरा टॅप करा",
//   "edit_post": "पोस्ट मध्ये फेरबदल करा",
//   "tag_people": "लोकांना टॅग करा",
//   "add_loc": "लोकेशन जोडा",
//   "some_field_are_missing": "काही फील्ड गहाळ आहे किंवा चुकीचे इनपुट आहे",
//   "please_add_loc": "कृपया लोकेशन जोडा",
//   "post_updated_success": "पोस्ट यशस्वीरित्या अपलोड झाली",
//   "post_created_success": "पोस्ट यशस्वी झाली.",
//   "upload_as": "अपलोड अशी करा",
//   "users": "युजरर्स",
//   "anonymous": "अनामिक",
//   "want_to_sell": "विकायचे आहे?",
//   "question": "प्रश्न",
//   "write_your_quest": "तुमचा प्रश्न लिहा",
//   "option_a": "पर्याय अ",
//   "option_b": "पर्याय ब",
//   "add_caption": "माहिती जोडा",
//   "add_more_item": "आणखी वस्तू जोडा",
//   "post": "पोस्ट",
//   "add_dish_detail": "डिश तपशील जोडा",
//   "please_select_delivery_option": "कृपया डिलिव्हरी पर्याय निवडा.",
//   "save": "जतन (सेव) करा",
//   "food_type": "खाण्याचे प्रकार?",
//   "veg": "शाकाहारी",
//   "non_veg": "मांसाहारी",
//   "name_of_dish": "डिशचे नाव",
//   "please_enter_dish_name": "कृपया डिशचे नाव इंटर करा",
//   "please_enter_valid_dish_name": "एक योग्य डिश नाव इंटर करा",
//   "cost": "खर्च",
//   "in_rs": "रु मध्ये",
//   "please_enter_dish_cost": "कृपया डिशची किंमत इंटर करा",
//   "please_enter_valid_dish_cost": "एक योग्य डिश खर्च इंटर करा",
//   "quantity": "प्रमाण",
//   "please_enter_quantity": "कृपया प्रमाण इंटर करा",
//   "please_enter_valid_quantity": "एक योग्य प्रमाण इंटर करा",
//   "prepration_time_in_min": "तयारीची वेळ (मिनिटात)",
//   "please_enter_prepration_time": "कृपया तयारीची वेळ इंटर करा",
//   "enter_valid_prepration_time": "एक योग्य तयारी वेळ इंटर करा",
//   "serve_per_person": "प्रति व्यक्ती सेवा",
//   "please_enter_serves_per_person": "कृपया प्रति व्यक्ती सेवा इंटर करा",
//   "enter_valid_serves_per_person": "प्रति व्यक्ती एक योग्य सेवा इंटर करा",
//   "search": "सर्च",
//   "item_already_exist_in_cart": "वस्तू आधीपासून कार्टमध्ये अस्तित्वात आहे",
//   "added_to_cart": "कार्टमध्ये जोडले",
//   "add_to_cart": "कार्टमध्ये जोडा",
//   "no_challenges_avail": "कोणतीही चॅलेंज उपलब्ध नाहीत",
//   "refresh": "रिफ्रेश करा",
//   "all": "सर्व",
//   "active": "सक्रिय",
//   "closed": "बंद",
//   "reward": "बक्षिसे",
//   "comments": "कॉमेंट्स",
//   "write_a_comment": "येथे कमेंट लिहा",
//   "like": "लाईक्स",
//   "view_comment": "कॉमेंट्स पहा",
//   "available": "उपलब्ध",
//   "qty_avail": "उपलब्ध प्रमाण ",
//   "share_post": "पोस्ट शेअर करा",
//   "bookmark": "बुकमार्क",
//   "report_post": "पोस्टचा रिपोर्ट द्या",
//   "explore": " एक्सप्लोरर",
//   "my_activity": "माझी अक्टिविटी ",
//   "other_activity": "इतर अक्टिविटी ",
//   "liked_your_post": "तुमची पोस्ट आवडली आहे ",
//   "you_have_liked_on": " तुम्हाला आवडले आहे",
//   "you_have_commented_on": "तुम्ही यावर कॉमेंट् केली आहे",
//   "comment_on_your_post": "तुमच्या पोस्टवर कॉमेंट् दिली",
//   "buy": "खरेदी करा",
//   "sell": "विका",
//   "data_not_found": "डेटा सापडला नाही.",
//   "order_id": "ऑर्डर आयडी",
//   "item_name": "वस्तूचे नाव",
//   "kitchen_addr": "स्वयंपाकघराचा पत्ता",
//   "delivering_to": " डिलिव्हरी करत आहे",
//   "intruction": "सूचना",
//   "gov_gst": "स. टॅक्स",
//   "public": "पब्लिक",
//   "hidden": "हिडन",
//   "my_product": "आमचं उत्पादन",
//   "my_order": "माझे ऑर्डर्स",
//   "search_user": "सर्च युजर",
//   "logout": "बाहेर पडा",
//   "setting": "सेटिंग्ज",
//   "choose_option": "पर्याय निवडा",
//   "cancel": "रद्द करा",
//   "capture_img": "फोटो कॅप्चर करा",
//   "capture_vid": "व्हिडिओ कॅप्चर करा",
//   "select_img": "फोटो निवडा",
//   "select_vid": "व्हिडिओ निवडा",
//   "my_followers": "माझे फॉलोस",
//   "my_following": "माझे फॉलोइस",
//   "no_data_available": "माहिती उपलब्ध नाही",
//   "followers": "फॉलोस",
//   "following": "फॉलोइस",
//   "descp": "माहिती",
//   "you_will_get_reward_after_wining_this_challenge":
//       "टीप: हे चॅलेंज जिंकल्यानंतर तुम्हाला बक्षीस मिळेल!",
//   "reward_are": "बक्षीस आहेत",
//   "chats": "मेसेज",
//   "group": "ग्रुप",
//   "select_img_where_you_want_to_pickup":
//       "तुम्हाला फाइल कोठून उचलायची आहे ते निवडा",
//   "camera": "कॅमेरा",
//   "gallery": "गॅलरी",
//   "enter_group_name": "ग्रुप नाव आणि पर्यायी प्रोफाइल पिक्चर प्रदान करा",
//   "provide_group_name_optional_image": "एक ग्रुप प्रोफाइल पिक्चर निवडा",
//   "select_group_image": "एक ग्रुप प्रोफाइल पिक्चर निवडा",
//   "participants": "सहभागी",
//   "new_group": "नवीन ग्रुप",
//   "group_name_cant_be_empty": "ग्रुप नाव रिक्त असू शकत नाही",
//   "type_message": "मेसेज लिहा",
//   "create_group": "ग्रुप तयार करा",
//   "select_atleast_2_members":
//       "ग्रुप तयार करण्यासाठी तुम्हाला किमान 2 सदस्य जोडावे लागतील",
//   "you_have_not_selected_members":
//       "तुम्ही जोडण्यासाठी कोणताही सदस्य निवडलेला नाही",
//   "add": "जोडा",
//   "next": "पुढे",
//   "deleted": "डिलिटड",
//   "no_conversations": "संभाषण नाही",
//   "create_new_group": "नवीन ग्रुप तयार करा",
//   "delete_group": "ग्रुप डिलिट",
//   "admin": "अडमिन",
//   "update_group_name": " ग्रुप नाव बदला  करा",
//   "group_will_be_deleted":
//       "ग्रुप डिलिट जाईल आणि पुनर्प्राप्त केला जाऊ शकत नाही",
//   "delete": " डिलिट",
//   "cou_cou": "cou_cou",
//   "challenges": "चॅलेंज",
//   "hungry": "हंग्री",
//   "clear": "क्लिअर",
//   "enter_your_addr": "तुमचा पत्ता इंटर करा",
//   "loading": "लोड करत आहे",
//   "days_ago": "दिवसांपूर्वी",
//   "hr_ago": "तास पूर्वी",
//   "min_ago": "मिनिटापूर्वी",
//   "my_addr": "माझा पत्ता",
//   "add_addr": "पत्ता जोडा",
//   "logout_from_cou_cou": "cou_cou मधून लॉगआउट?",
//   "you_wont_receive_existing": "तुम्हाला कोणतीही ऑफर भेटली नाही.",
//   "this_challenge_is_expired": "हे चॅलेंज कालबाह्य झाले आहे",
//   "no_reels_avail": "कोणतीही रील उपलब्ध नाही",
//   "could_not_connect_to_internet": "इंटरनेटशी कनेक्ट होऊ शकले नाही",
//   "order_placed_on": "ऑर्डर दिली"
};
