name: coucou_v2
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 9.0.0+34

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.2
  cached_network_image: ^3.2.2
  get_storage: ^2.0.3
  fluttertoast: ^8.1.1
  carousel_slider: ^4.1.1
  transparent_image: ^2.0.0
  url_launcher: ^6.1.7
  path_provider: ^2.0.11
  smooth_page_indicator: ^1.0.0+2
  device_info_plus: ^3.2.4
  flutter_spinkit: ^5.1.0
  timeago: ^3.3.0
  inview_notifier_list: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  pull_to_refresh_flutter3: ^2.0.1
  photo_gallery: ^2.1.1
  in_app_update: ^4.0.1
  camera: ^0.10.5+5
  image_picker: ^1.0.0
  uuid: ^3.0.6
  share_plus: ^6.3.0
  video_player: ^2.7.2
  scrollable_positioned_list: ^0.3.5
  animations: ^2.0.7
  email_validator: ^2.1.17
  app_settings: ^4.1.5
  video_thumbnail: ^0.5.3
  filesize: ^2.0.1
  retry: ^3.1.0
  permission_handler: ^10.3.0
  go_router: ^11.1.2
  dismissible_page: ^1.0.2
  crop_your_image: ^0.7.4
  sms_autofill: ^2.2.0
  get: ^4.6.6
  image_editor_plus: ^1.0.3
  # flutter_ffmpeg: null
  on_audio_query: ^2.9.0
  file_picker: ^6.0.0
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  package_info_plus: ^4.0.2
  photo_manager: ^2.8.0
  # flutter_sound: ^9.2.13
  # audio_session: ^0.1.16
  record: ^5.0.1
  # audioplayers: ^5.2.0
  palette_generator: ^0.3.3+3
  flutter_windowmanager: ^0.2.0
  intl: ^0.18.1
  image_gallery_saver: ^2.0.3
  image_watermark: ^0.0.5
  showcaseview: ^2.0.3
  video_compress: ^3.1.2
  flutter_localizations: 
    sdk: flutter

  geolocator: ^8.2.0
  geocoding: ^2.0.4
  # location: ^5.0.3

  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_messaging: ^14.6.9
  firebase_dynamic_links: ^5.0.11
  firebase_analytics: ^10.1.6
  firebase_remote_config: ^4.2.1
  # google_sign_in: 5.0.2
  # flutter_facebook_auth: ^5.0.6
  flutter_branch_sdk: ^6.6.0

  amplify_flutter: ^1.5.0
  amplify_auth_cognito: ^1.5.0
  amplify_storage_s3: ^1.5.0

dependency_overrides:
  device_info_plus: ^3.2.4
  device_info_plus_windows: 2.1.1
  package_info_plus: ^4.0.1
  win32: ^3.0.0
  ffi: ^1.0.0
  flutter_image_compress: ^1.1.3
  image: ^4.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/launcher_icons/launcher_icon.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/login_screen_images/
    - assets/images/select_language_images/
    - assets/icons/
    - assets/icons/nav_bar_icons/
    - assets/icons/common_icons/
    - assets/lottie/
    - assets/audio/beep_sound.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Black.ttf
          weight: 900
    - family: Amiko
      fonts:
        - asset: assets/fonts/Amiko/Amiko-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amiko/Amiko-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Amiko/Amiko-Bold.ttf
          weight: 700
    - family: Inika
      fonts:
        - asset: assets/fonts/Inika/Inika-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inika/Inika-Bold.ttf
          weight: 700
    - family: Umba Soft
      fonts:
        - asset: assets/fonts/UmbaSoft/UmbaSoft-Regular.otf
          weight: 400
        - asset: assets/fonts/UmbaSoft/UmbaSoft-Bold.otf
          weight: 700
        - asset: assets/fonts/UmbaSoft/UmbaSoft-Light.otf
          weight: 300
        - asset: assets/fonts/UmbaSoft/UmbaSoft-Medium.otf
          weight: 500
        - asset: assets/fonts/UmbaSoft/UmbaSoft-Thin.otf
          weight: 200
    
       
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
